React capstone project - Metrics webapp
lily-coder/metrics-webapp pull request #5
Opened 2021-10-23 19:52 UTC by lily-coder

In this API I have selected an API that provides numeric data about a COVID-19 cases reports in Africa

The Homepage shows the COVID-19 cases in the African countries and when the user clicks on the country, the user is navigated to a page with the country details.
Here is the loom video [link](https://www.loom.com/share/63bf33d4ece44aee9479bfeb32615c5c)

2021-10-23 20:57 UTC, oloomoses requested changes
Hi @lily-coder, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

_Slack: Oloo Moses_
------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-10-23 20:57 UTC, oloomoses commented on README.md
> +[Live Demo Link](https://metricswebapp200.herokuapp.com/)
- [x] Kindly record a video presentation of the project highlighting all the project features and a piece of code you are proud of. Remember to add the video presentation link in the readme as per the project requirements.

2021-10-23 20:57 UTC, oloomoses commented on README.md
> +
- [x] Kindly add an acknowledgment section and give credit to Nelson Sakwa, creator of the original design as per the project requirements.

2021-10-23 20:57 UTC, oloomoses commented on src/components/Navbar.js
> +import React from 'react';
- [ ] The linters are there to enforce code quality and should not be disabled. Kindly enable the linters and fix the issues raised.

2021-10-23 20:57 UTC, oloomoses commented on src/pages/CountriesPage.js
> +import { FaGlobeAfrica } from 'react-icons/fa';
- [x] The linters are there to enforce code quality and should not be disabled. Kindly enable the linters and fix the issues raised.

2021-10-23 20:57 UTC, oloomoses commented on src/redux/ConfigStore.js
> +
- [x] Please do not log redux data on the browser console as it may cause site security issues. Kindly clear the logged data displayed on the browser console.

2021-10-23 20:57 UTC, oloomoses commented on README.md
> +
- [x] This sentence is incomplete and has some grammar errors. Kindly use Grammarly to check and correct it so as to make your readme more descriptive.

2021-10-23 20:57 UTC, oloomoses commented on src/components/Navbar.js
> +  );
- [x] Kindly add all the icons in the navbar as they appear to match that of the given design. Check the screenshot belo
![Screenshot from 2021-10-23 21-19-00](https://user-images.githubusercontent.com/20245164/138571234-1e880af2-4220-4daf-a7a2-e18328a1aa00.png)
w

2021-10-23 20:57 UTC, oloomoses commented on src/pages/CountriesPage.js
> +          {countries.map((country) => (
- [x] Kindly create a filter component to allow a user to filter data with some parameters as per the project requirements.
![Screenshot from 2021-09-09 20-23-55](https://user-images.githubusercontent.com/20245164/132733854-6502a226-d437-4406-ad56-49900e3d1915.png)

- [x] The filter should be a stateless component
![Screenshot from 2021-09-09 20-23-02](https://user-images.githubusercontent.com/20245164/132733891-79c40cc3-b23b-44af-802c-08197aacc662.png)

2021-10-25 08:46 UTC, arslanbisharat requested changes
# Changes Requested, 

Hi there, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have limited number of code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2021-10-25 08:46 UTC, arslanbisharat commented on src/__tests__/CountriesPage.Test.js
> +
- [x] Tests are being failed. Please make sure you have all tests passed and please add more tests. 
<img width="685" alt="Capture" src="https://user-images.githubusercontent.com/58504655/138663437-82acfb1a-0f6e-40dd-8d28-4833aa4a8702.PNG">

2021-10-25 08:46 UTC, arslanbisharat commented on README.md
> +[Live Demo Link](https://metricswebapp200.herokuapp.com/)
The video you have added is Pull Request is not enough. 

```
The maximum length of the video is 5 minutes.
The video contains a clear and objective description of the project in professional English. The topic and purpose of the project are made clear.
The video contains a demo of the project, highlighting all the project features.
The video contains a highlight about a piece of the code the student finds interesting or is proud of making.
```

2021-10-25 09:51 UTC, arslanbisharat approved these changes
# Approved 👏 

Hi there, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

To Highlight: 
- The Pull Request has a proper title and description. ✔️ 
- You have added a descriptive Readme file. Good Job. ✔️ 
- There is no linter error is present. ✔️ 
- Project has met all the technical aspects you needed for this project. Keep rocking! ✔️ 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of code reviews per project which you can see from your dashboard. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)_

2021-10-25 09:56 UTC, lily-coder commented
Thank you for the reviews

2021-10-25 09:56 UTC, merged